-- MySQL Script generated by MySQL Workbench
-- Tue May 21 09:38:27 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SST_Engefame
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SST_Engefame
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SST_Engefame` DEFAULT CHARACTER SET utf8 ;
USE `SST_Engefame` ;

-- -----------------------------------------------------
-- Table `SST_Engefame`.`Categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SST_Engefame`.`Categorias` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SST_Engefame`.`Funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SST_Engefame`.`Funcionarios` (
  `Nome` VARCHAR(100) NOT NULL,
  `CPF` VARCHAR(14) NOT NULL,
  `Situacao` TINYINT NOT NULL,
  `Categorias_idCategoria` INT NULL,
  PRIMARY KEY (`CPF`, `Categorias_idCategoria`),
  INDEX `fk_Funcionarios_Categorias1_idx` (`Categorias_idCategoria` ASC) VISIBLE,
  CONSTRAINT `fk_Funcionarios_Categorias1`
    FOREIGN KEY (`Categorias_idCategoria`)
    REFERENCES `SST_Engefame`.`Categorias` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SST_Engefame`.`Treinamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SST_Engefame`.`Treinamentos` (
  `idTreinamento` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Subtitulo` VARCHAR(100) NOT NULL,
  `Descricao` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idTreinamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SST_Engefame`.`Empresas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SST_Engefame`.`Empresas` (
  `idEmpresa` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  PRIMARY KEY (`idEmpresa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SST_Engefame`.`Turmas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SST_Engefame`.`Turmas` (
  `idTurma` INT NOT NULL AUTO_INCREMENT,
  `Empresas_idEmpresa` INT NOT NULL,
  `Treinamentos_idTreinamento` INT NOT NULL,
  `Data_Realizacao` DATE NOT NULL,
  `Data_Validade` DATE NOT NULL,
  `Comprovacao` TINYINT NOT NULL,
  `Modalidade` TINYINT NOT NULL,
  `Carga_Horaria` TIME NOT NULL,
  `Preco_Unitario` DECIMAL(10,2) NOT NULL,
  `Curso_Pago` TINYINT NOT NULL,
  `Instrutor` VARCHAR(45) NULL,
  PRIMARY KEY (`idTurma`, `Empresas_idEmpresa`, `Treinamentos_idTreinamento`),
  INDEX `fk_Historico_Treinamentos_Treinamentos1_idx` (`Treinamentos_idTreinamento` ASC) VISIBLE,
  INDEX `fk_Turmas_Empresas1_idx` (`Empresas_idEmpresa` ASC) VISIBLE,
  CONSTRAINT `fk_Historico_Treinamentos_Treinamentos1`
    FOREIGN KEY (`Treinamentos_idTreinamento`)
    REFERENCES `SST_Engefame`.`Treinamentos` (`idTreinamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Turmas_Empresas1`
    FOREIGN KEY (`Empresas_idEmpresa`)
    REFERENCES `SST_Engefame`.`Empresas` (`idEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SST_Engefame`.`Acompanhamento_Turmas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SST_Engefame`.`Acompanhamento_Turmas` (
  `idAcompanhamento` INT NOT NULL AUTO_INCREMENT,
  `Data_Inclusao` DATE NOT NULL,
  `Data_Prazo` DATE NULL,
  `Descricao` LONGTEXT NOT NULL,
  `Turmas_idTurma` INT NOT NULL,
  `Turmas_Empresas_idEmpresa` INT NOT NULL,
  `Turmas_Treinamentos_idTreinamento` INT NOT NULL,
  PRIMARY KEY (`idAcompanhamento`, `Turmas_idTurma`, `Turmas_Empresas_idEmpresa`, `Turmas_Treinamentos_idTreinamento`),
  INDEX `fk_Acompanhamento_Turmas_Turmas1_idx` (`Turmas_idTurma` ASC, `Turmas_Empresas_idEmpresa` ASC, `Turmas_Treinamentos_idTreinamento` ASC) VISIBLE,
  CONSTRAINT `fk_Acompanhamento_Turmas_Turmas1`
    FOREIGN KEY (`Turmas_idTurma` , `Turmas_Empresas_idEmpresa` , `Turmas_Treinamentos_idTreinamento`)
    REFERENCES `SST_Engefame`.`Turmas` (`idTurma` , `Empresas_idEmpresa` , `Treinamentos_idTreinamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SST_Engefame`.`Turmas_has_Funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SST_Engefame`.`Turmas_has_Funcionarios` (
  `Turmas_idTurma` INT NOT NULL,
  `Turmas_Empresas_idEmpresa` INT NOT NULL,
  `Turmas_Treinamentos_idTreinamento` INT NOT NULL,
  `Funcionarios_CPF` VARCHAR(14) NOT NULL,
  `Funcionarios_Categorias_idCategoria` INT NOT NULL,
  PRIMARY KEY (`Turmas_idTurma`, `Turmas_Empresas_idEmpresa`, `Turmas_Treinamentos_idTreinamento`, `Funcionarios_CPF`, `Funcionarios_Categorias_idCategoria`),
  INDEX `fk_Turmas_has_Funcionarios_Funcionarios1_idx` (`Funcionarios_CPF` ASC, `Funcionarios_Categorias_idCategoria` ASC) VISIBLE,
  INDEX `fk_Turmas_has_Funcionarios_Turmas1_idx` (`Turmas_idTurma` ASC, `Turmas_Empresas_idEmpresa` ASC, `Turmas_Treinamentos_idTreinamento` ASC) VISIBLE,
  CONSTRAINT `fk_Turmas_has_Funcionarios_Turmas1`
    FOREIGN KEY (`Turmas_idTurma` , `Turmas_Empresas_idEmpresa` , `Turmas_Treinamentos_idTreinamento`)
    REFERENCES `SST_Engefame`.`Turmas` (`idTurma` , `Empresas_idEmpresa` , `Treinamentos_idTreinamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Turmas_has_Funcionarios_Funcionarios1`
    FOREIGN KEY (`Funcionarios_CPF` , `Funcionarios_Categorias_idCategoria`)
    REFERENCES `SST_Engefame`.`Funcionarios` (`CPF` , `Categorias_idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
